[project]
name = "try-copier"
version = "0.1.16"
description = "try updating from this remote"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "copier>=9.11.3",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
]
