[project]
name = "try-copier"
version = "0.1.8"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "copier>=9.11.3",
    "pre-commit>=4.5.1",
]
